---
title: "COVID19 PE"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rnaturalearth)
library(mapview)
peru <- ne_states(country = 'peru')


library (raster)
library(rgdal)
#cargamos el shape
dist.map <- readOGR(dsn="C:/Users/Lenovo/Desktop/covid_pe/data/distritos/DISTRITOS.shp")

LIMA_METRO <- c("150101","150102","150103","150104","150105","150106","150107","150108","150109",
  "150110","150111","150112", "150113", "150114","150115","150116","150117","150118",
  "150119","150120","150121","150122","150123","150124","150125",  "150126","150127","150128",
  "150129","150130","150131","150132","150133","150134","150135","150136","150137","150138",
  "150139","150140","150141","150142","150143")#CREAMOS EL OBJETO region que guarda el nombre ICA

distritos_lima <- dist.map[as.character(dist.map@data$IDDIST) %in% LIMA_METRO, ]


```



Resumen
=======================================================================

Row
-----------------------------------------------------------------------



### Acumulado de Casos Positivos

```{r}
n=835456
valueBox(n, icon = "fa-user-md",color = "purple")

```


### Casos Activos

```{r}
n=835456
valueBox(n, icon = "fa-user-plus",color = "orange")

```




### Casos Recuperados

```{r}
#comments <- computeComments()
valueBox(20564, icon = "fa-street-view",color = "forestgreen")
```

### Hospitalizados

```{r}
#spam <- computeSpam()
valueBox(9255, icon = "fa-hospital-o",color = "red")

```



### Camas UCI

```{r}
#comments <- computeComments()
valueBox(1205, icon = "fa-bed",color = "teal")
```

### Fallecidos

```{r}
#spam <- computeSpam()
valueBox(30000, icon = "fa-heartbeat",color = "olive")

```





Column {data-width=750}
-----------------------------------------------------------------------

### Número total de casos por departamento

```{r}
mapview(peru)
```








Column {data-width=750}
-----------------------------------------------------------------------

### Lima Metropolitana

```{r}
mapview(distritos_lima)
```

Spatitial
=======================================================================



Column {data-width=650}
-----------------------------------------------------------------------

### Chart D

```{r}

```


